[package]
name = "sozu-e2e"
version = "0.15.17"
rust-version = "1.70.0"
edition = "2021"

[dependencies]
kawa = "0.6.3"
futures = "^0.3.28"
hyper = { version = "^0.14.27", features = ["client", "http1"] }
hyper-rustls = { version = "^0.24.1", default-features = false, features = ["webpki-tokio", "http1", "tls12", "logging"] }
libc = "^0.2.149"
mio = "^0.8.8"
rustls = { version = "^0.21.7", features = ["dangerous_configuration"] }
slab = "^0.4.9"
time = "^0.3.29"
tokio = { version = "1.33.0", features = ["net", "rt-multi-thread"] }

sozu-command-lib = { path = "../command", version = "^0.15.17" }
sozu-lib = { path = "../lib", version = "^0.15.17" }
