---
name: CI
on: [ push, pull_request ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        rust:
          - stable
          - beta
        include:
          - rust: nightly
            experimental: true
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run cargo clippy --fix (check for unapplied lints)
        run: |
          cargo clippy --all-targets --all-features -- -D warnings --fix --allow-dirty --allow-staged
          git diff --exit-code
      - name: Build
        run: cargo build ${{ matrix.features }}
      - name: Test
        run: cargo test --verbose ${{ matrix.features }}
  doc:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo doc --verbose
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run cargo tarpaulin
        env:
          TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: cargo tarpaulin --coveralls $TOKEN
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Install protobuf-compiler
        shell: powershell
        run: |
          $PROTOC_VERSION = "3.19.4"
          $PROTOC_ZIP = "protoc-$PROTOC_VERSION-win64.zip"
          $PROTOC_URL = "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP"
          $PROTOC_DIR = "$env:USERPROFILE\protoc"
          Invoke-WebRequest -Uri $PROTOC_URL -OutFile $PROTOC_ZIP
          Expand-Archive -Path $PROTOC_ZIP -DestinationPath $PROTOC_DIR -Force
          echo "$PROTOC_DIR\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          Remove-Item $PROTOC_ZIP
          protoc --version
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test --verbose
...
