---
name: CI
on: [ push, pull_request ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        rust:
          - stable
          - beta
        include:
          - rust: nightly
            experimental: true
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose ${{ matrix.features }}
  doc:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cargo-tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin
      - name: Run cargo tarpaulin
        uses: actions-rs/cargo@v1
        env:
          TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        with:
          command: tarpaulin
          args: --coveralls $TOKEN
  dockerhub:
    name: Docker build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: 'true'
          tags: clevercloud/sozu:${{ github.sha }}
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Install protobuf-compiler
        shell: powershell
        run: |
          $PROTOC_VERSION = "3.19.4"
          $PROTOC_ZIP = "protoc-$PROTOC_VERSION-win64.zip"
          $PROTOC_URL = "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP"
          $PROTOC_DIR = "$env:USERPROFILE\protoc"
          Invoke-WebRequest -Uri $PROTOC_URL -OutFile $PROTOC_ZIP
          Expand-Archive -Path $PROTOC_ZIP -DestinationPath $PROTOC_DIR -Force
          echo "$PROTOC_DIR\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          Remove-Item $PROTOC_ZIP
          protoc --version
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
...
